version: '3'

services:
  web:
    command: bash -c "python manage.py collectstatic --noinput && sleep 5 && python manage.py migrate && python manage.py loaddata fixtures/*.json && cron && python manage.py runserver 0.0.0.0:8000"
    volumes:
        - ./rapstore-django/django:/code
        - applications:/apps
        - riot:/RIOT
    ports:
      - "${BPORT}:8000"
  frontend:
    ports:
      - "${FPORT}:4200"
    volumes:
        - ./rapstore-django/rapstore-frontend:/app
        - /app/node_modules
    command: ng serve --host=0.0.0.0 ${AFLAGS} --poll
volumes:
    applications:
    riot:
