version: '2'

services:
  db:
    image: postgres
  web:
    build: 
        context: ./rapstore-django/django
        dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
        - ./rapstore-django/django:/code
        - applications:/apps
    depends_on:
      - db
  frontend:
    build: 
        context: ./rapstore-django/rapstore-frontend
        dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
        - ./rapstore-django/rapstore-frontend:/app
        - /app/node_modules
  builder:
    build:
        context: ./rapstore-django/builder
        dockerfile: Dockerfile
    command: bash -c "chmod +x /code/docker-entry.sh && /code/docker-entry.sh"
    volumes:
      - ./rapstore-django/builder:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
volumes:
    applications:
