version: '3'

services:
  db:
    restart: always
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    restart: always
    build: 
        context: ./rapstore-django/django
        dockerfile: Dockerfile
    environment:
      - GITHUB_CLIENT_ID
      - GITHUB_SECRET_KEY
      - DEBUG
      - SECRET_KEY
    depends_on:
      - db
  frontend:
    restart: always
    build: 
        context: ./rapstore-django/rapstore-frontend
        dockerfile: Dockerfile
  redis:
    restart: always
    image: redis:latest

  celery:
    restart: always
    build:
        context: ./rapstore-django/celery
        dockerfile: Dockerfile
    command: celery worker --app=api.tasks
    environment:
      - DEBUG
      - SECRET_KEY
    volumes:
      - ./rapstore-django/django:/code
      - riot:/RIOT
      - raw:/raw

volumes:
    postgres-data:
    raw:
