version: '2'

services:
  db:
    image: postgres
  web:
    build: 
        context: ./rapstore-django/django
        dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
        - ./rapstore-django/django:/code
    depends_on:
      - db
  frontend:
    build: 
        context: ./rapstore-django/rapstore-frontend
        dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
        - ./rapstore-django/rapstore-frontend:/app
