version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: 
        context: ./rapstore-django/django
        dockerfile: Dockerfile
    environment:
      - GITHUB_CLIENT_ID
      - GITHUB_SECRET_KEY
      - DEBUG
      - SECRET_KEY
    depends_on:
      - db
  frontend:
    build: 
        context: ./rapstore-django/rapstore-frontend
        dockerfile: Dockerfile
  builder:
    build:
        context: ./rapstore-django/builder
        dockerfile: Dockerfile
    volumes:
      - ./rapstore-django/builder:/code
      - riot:/RIOT
    depends_on:
      - db
    environment:
      - DEBUG
      - SECRET_KEY

  redis:
     image: redis:latest

  celery:
    build:
        context: ./rapstore-django/celery
        dockerfile: Dockerfile
    command: celery worker --app=api.tasks
    environment:
      - DEBUG
      - SECRET_KEY
    volumes:
      - ./rapstore-django/django:/code
      - riot:/RIOT

volumes:
    postgres-data:
