version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: 
        context: ./rapstore-django/django
        dockerfile: Dockerfile
    environment:
      - GITHUB_CLIENT_ID
      - GITHUB_SECRET_KEY
    volumes:
        - ./rapstore-django/django:/code
        - applications:/apps
        - riot:/RIOT
    depends_on:
      - db
  frontend:
    build: 
        context: ./rapstore-django/rapstore-frontend
        dockerfile: Dockerfile
    command: ng serve --host=0.0.0.0 ${AFLAGS}
    volumes:
        - ./rapstore-django/rapstore-frontend:/app
        - /app/node_modules
  builder:
    build:
        context: ./rapstore-django/builder
        dockerfile: Dockerfile
    command: bash -c "chmod +x /code/docker-entry.sh && /code/docker-entry.sh"
    volumes:
      - ./rapstore-django/builder:/code
      - riot:/RIOT
    depends_on:
      - db
volumes:
    applications:
    riot:
